<?php

require_once dirname(__FILE__) . '/../../../application/models/Article.php';

/**
 * Test class for Article.
 * Generated by PHPUnit on 2011-12-01 at 10:17:22.
 */
class ArticleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Article
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Article;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
